### PR TITLE
Implement PEP 526 Variable Annotations Syntax

### PR DESCRIPTION
**Pull request by ilevkivskyi**
@ddfisher @gvanrossum @JukkaL 

Here is an implementation of the PEP 526 syntax with minimal changes in typed_ast API. The only externally visible change is:
```
Assign(expr* targets, expr? value, expr? type_comment)
```
This requires a tiny change to ``mypy/fastparse.py``, there is an accompanying PR to mypy with this change.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Since this is just a backport of the corresponding Python 3.6 code I'm going to merge this mostly based on trust. I'll iterate once I've got most things working again.

**Comment by gvanrossum** [comment]
Never mind I don't have commit access to this repo, and David's out this week. :-(

**Comment by ilevkivskyi** [comment]
@gvanrossum 
OK, no problem.
Anyway, I changed behaviour a bit in response to your latest e-mail: ``x: int`` is now equivalent to ``x = None # type: int`` and both are always OK, while ``x: int = None`` is flagged as error if ``--strict-optional``.

Did I understand you correct?

I am now testing this and will update PRs (here and at mypy) soon.

**Comment by gvanrossum** [comment]
Those behaviors sound okay. I am now testing too. Two administrative nits I found:

- This PR should bump the version in setup.py
- Should we rename ast35 to ast36???

**Comment by ilevkivskyi** [comment]
@gvanrossum 
> This PR should bump the version in setup.py

OK, will do this

> Should we rename ast35 to ast36???

There is also a third option to keep both (see my comment at mypy PR)

**Comment by ddfisher** [comment]
This isn't compatible with the current mypy, so I'll need to wait until https://github.com/python/mypy/pull/2131 is pushed to PyPI before releasing this.

**Comment by ilevkivskyi** [comment]
@ddfisher I thought that you are supposed to review and merge https://github.com/python/mypy/pull/2131 That one should work with both old and new versions of typed_ast.

**Comment by ddfisher** [comment]
Yep!  That's the plan.  I just wanted to make a note here about the need to wait for a mypy release before releasing this.

**Comment by ddfisher** [comment]
Actually, I chatted with Guido a bit about this, and we'd like to remove that dependency problem.  Here's how that could be done: instead of putting the assignment type annotation in the same field as the type comment, leave the type comment field as is and add a new one for the type annotation.  This is similar to how function annotations/type comments are handled.  Also, I think this would get rid of the need for the new_syntax field, which would be a nice simplification.  Would you mind making these changes?

**Comment by ilevkivskyi** [comment]
OK, I will do this. I will push commits here and to mypy PR together with implementing your comments (not sure that I will have time to do all this today).

**Comment by ddfisher** [comment]
Thanks!

**Comment by ilevkivskyi** [comment]
@ddfisher I updated all the three PRs (here, mypy, and typeshed) taking into account your comments.
Now all four combinations of mypy and typed_ast (old-old, old-new, new-old, new-new) should work.
Please double check.

**Comment by ddfisher** [comment]
Had to make some minor tweaks, but this looks good now.  Thanks!

**Pull request merged**
